package com.groove.music.data.repository

import com.groove.music.core.database.dao.PlaylistDao
import com.groove.music.core.database.entity.PlaylistEntity
import com.groove.music.core.database.entity.PlaylistSongCrossRef
import com.groove.music.data.mapper.PlaylistMapper.toDomainList
import com.groove.music.domain.model.Playlist
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Mirrors all playlist operations from useLibraryStore:
 * createPlaylist, deletePlaylist, renamePlaylist,
 * addSongsToPlaylist, removeSongFromPlaylist.
 */
@Singleton
class PlaylistRepository @Inject constructor(
    private val playlistDao: PlaylistDao
) {
    val allPlaylists: Flow<List<Playlist>> =
        playlistDao.observeAllWithSongs().map { it.toDomainList() }

    suspend fun getWithSongs(id: Long): Playlist? =
        playlistDao.getWithSongs(id)?.let {
            com.groove.music.data.mapper.PlaylistMapper.run { it.toDomain() }
        }

    /** Mirrors createPlaylist in useLibraryStore */
    suspend fun create(
        name: String,
        description: String? = null,
        emoji: String? = "🎵",
        isAutoGenerated: Boolean = false
    ): Long = playlistDao.insert(
        PlaylistEntity(
            name            = name,
            description     = description,
            emoji           = emoji,
            isAutoGenerated = isAutoGenerated
        )
    )

    /** Mirrors deletePlaylist */
    suspend fun delete(id: Long) = playlistDao.deleteById(id)

    /** Mirrors renamePlaylist */
    suspend fun rename(id: Long, newName: String) = playlistDao.rename(id, newName)

    /** Mirrors addSongsToPlaylist */
    suspend fun addSongs(playlistId: Long, songIds: List<Long>) {
        val maxPos = playlistDao.getMaxPosition(playlistId) ?: -1
        val crossRefs = songIds.mapIndexed { i, songId ->
            PlaylistSongCrossRef(playlistId, songId, maxPos + 1 + i)
        }
        playlistDao.addSongsToPlaylist(crossRefs)
    }

    suspend fun addSong(playlistId: Long, songId: Long) = addSongs(playlistId, listOf(songId))

    /** Mirrors removeSongFromPlaylist */
    suspend fun removeSong(playlistId: Long, songId: Long) =
        playlistDao.removeSongFromPlaylist(playlistId, songId)

    /** Called when a song is deleted — removes it from all playlists */
    suspend fun removeSongFromAll(songId: Long) =
        playlistDao.removeSongFromAllPlaylists(songId)

    /**
     * Upsert an auto-generated folder playlist.
     * Mirrors the auto-playlist creation logic in syncFolderSongs (store.js).
     */
    suspend fun upsertFolderPlaylist(folderName: String, songIds: List<Long>) {
        val existing = playlistDao.findAutoGeneratedByName(folderName)
        val playlistId = if (existing != null) {
            existing.id
        } else {
            playlistDao.insert(
                PlaylistEntity(
                    name            = folderName,
                    description     = "Songs from folder: $folderName",
                    emoji           = "📁",
                    isAutoGenerated = true
                )
            )
        }
        addSongs(playlistId, songIds)
    }
}
