package com.groove.music.core.database.dao

import androidx.room.*
import com.groove.music.core.database.entity.PlaylistEntity
import com.groove.music.core.database.entity.PlaylistSongCrossRef
import com.groove.music.core.database.entity.PlaylistWithSongs
import kotlinx.coroutines.flow.Flow

@Dao
interface PlaylistDao {

    // ── Observe playlists (reactive) ──────────────────────────────────────────
    @Transaction
    @Query("SELECT * FROM playlists ORDER BY createdAt DESC")
    fun observeAllWithSongs(): Flow<List<PlaylistWithSongs>>

    @Query("SELECT * FROM playlists ORDER BY createdAt DESC")
    fun observeAll(): Flow<List<PlaylistEntity>>

    // ── One-shot ──────────────────────────────────────────────────────────────
    @Transaction
    @Query("SELECT * FROM playlists WHERE id = :id LIMIT 1")
    suspend fun getWithSongs(id: Long): PlaylistWithSongs?

    @Query("SELECT * FROM playlists")
    suspend fun getAll(): List<PlaylistEntity>

    // ── Auto-generated playlist lookup (mirrors isAutoGenerated check in web) ─
    @Query("""
        SELECT * FROM playlists
        WHERE isAutoGenerated = 1
        AND LOWER(name) = LOWER(:name)
        LIMIT 1
    """)
    suspend fun findAutoGeneratedByName(name: String): PlaylistEntity?

    // ── CRUD ──────────────────────────────────────────────────────────────────
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(playlist: PlaylistEntity): Long

    @Update
    suspend fun update(playlist: PlaylistEntity)

    @Query("UPDATE playlists SET name = :newName WHERE id = :id")
    suspend fun rename(id: Long, newName: String)

    @Query("DELETE FROM playlists WHERE id = :id")
    suspend fun deleteById(id: Long)

    // ── Song membership (mirrors addSongsToPlaylist / removeSongFromPlaylist) ──
    @Insert(onConflict = OnConflictStrategy.IGNORE)
    suspend fun addSongToPlaylist(crossRef: PlaylistSongCrossRef)

    @Insert(onConflict = OnConflictStrategy.IGNORE)
    suspend fun addSongsToPlaylist(crossRefs: List<PlaylistSongCrossRef>)

    @Query("DELETE FROM playlist_songs WHERE playlistId = :playlistId AND songId = :songId")
    suspend fun removeSongFromPlaylist(playlistId: Long, songId: Long)

    @Query("DELETE FROM playlist_songs WHERE songId = :songId")
    suspend fun removeSongFromAllPlaylists(songId: Long)

    @Query("SELECT COUNT(*) FROM playlist_songs WHERE playlistId = :playlistId")
    suspend fun getSongCount(playlistId: Long): Int

    @Query("SELECT MAX(position) FROM playlist_songs WHERE playlistId = :playlistId")
    suspend fun getMaxPosition(playlistId: Long): Int?
}
