package com.groove.music.domain.model

/**
 * Domain model for a playlist with its resolved songs.
 * Mirrors the playlist shape in playlistStore.js and Playlists.jsx.
 */
data class Playlist(
    val id: Long,
    val name: String,
    val description: String?,
    val emoji: String?,
    val isAutoGenerated: Boolean,   // folder playlists (📁 badge in UI)
    val songs: List<Song>,
    val createdAt: Long
)
