package com.groove.music.data.mapper

import com.groove.music.core.database.entity.PlaylistEntity
import com.groove.music.core.database.entity.PlaylistWithSongs
import com.groove.music.domain.model.Playlist
import com.groove.music.data.mapper.SongMapper.toDomain

object PlaylistMapper {

    fun PlaylistWithSongs.toDomain(): Playlist = Playlist(
        id              = playlist.id,
        name            = playlist.name,
        description     = playlist.description,
        emoji           = playlist.emoji,
        isAutoGenerated = playlist.isAutoGenerated,
        songs           = songs.map { it.toDomain() },
        createdAt       = playlist.createdAt
    )

    fun List<PlaylistWithSongs>.toDomainList(): List<Playlist> = map { it.toDomain() }
}
