package com.groove.music.core.database.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Mirrors the IndexedDB `playlists` table.
 *
 * isAutoGenerated = true for folder playlists created automatically
 * during scan (mirrors isAutoGenerated in PlaylistImporter / syncFolderSongs).
 */
@Entity(tableName = "playlists")
data class PlaylistEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    val name: String,
    val description: String? = null,
    val emoji: String? = null,

    // Auto-generated playlists are created by folder scan (📁 badge in UI)
    val isAutoGenerated: Boolean = false,

    val createdAt: Long = System.currentTimeMillis()
)
